apiVersion: v1
kind: Pod
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  containers:
    - name: streamlit
      image: arielizralevitch/test11
      imagePullPolicy: Always

      ports:
        - containerPort: 8000










